const state = { tests: [], dashboard: null, selectedTestId: null, lastSuccessAt: 0 };
const $ = (id) => document.getElementById(id);
const escapeHtml = (value) => String(value ?? '').replace(/[&<>"']/g, (char) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]));
const formatMetric = (value, key) => key.endsWith('_ms') ? `${Number(value).toFixed(1)} ms` : typeof value === 'number' ? value.toFixed(2) : value;

async function load() {
  const [dashboardResponse, testsResponse] = await Promise.all([fetch('/api/dashboard'), fetch('/api/tests')]);
  if (!dashboardResponse.ok || !testsResponse.ok) throw new Error('backend request failed');
  const [dashboard, tests] = await Promise.all([dashboardResponse.json(), testsResponse.json()]);
  state.dashboard = dashboard; state.tests = tests; state.lastSuccessAt = Date.now(); setHealth('ONLINE');
  if (state.selectedTestId && !tests.some((test) => test.evaluation.id === state.selectedTestId)) state.selectedTestId = null;
  renderDashboard(); renderTests();
}
function setHealth(status) { $('health-label').textContent = status; $('health').className = `live ${status.toLowerCase()}`; $('health-age').textContent = status === 'ONLINE' ? ' synced' : status === 'STALE' ? ' no recent sync' : status === 'OFFLINE' ? ' backend unavailable' : ' waiting for sync'; }
function renderDashboard() {
  const d = state.dashboard, current = state.tests.find((test) => test.evaluation.id === state.selectedTestId) || d.current_test, metrics = current?.evaluation?.metrics || {};
  $('version').textContent = d.current_version ? `v${d.current_version.version}` : '--'; $('model-marker').textContent = `MODEL ${d.model || '--'}`;
  $('headline').textContent = d.model ? `${d.model} / ${d.test_counts.total ? `test ${d.current_test_number}` : 'ready'}` : 'Atlas is ready';
  $('subhead').textContent = d.current_version ? d.current_version.name : 'Initialize Atlas and run the first experiment.';
  $('stats').innerHTML = [['Evaluations', d.test_counts.total], ['Passed', d.test_counts.passed], ['Failed', d.test_counts.failed], ['Experiments', d.experiment_count]].map(([label, value]) => `<div class="stat"><label>${label}</label><strong>${escapeHtml(value)}</strong></div>`).join('');
  $('test-title').textContent = current ? `${state.selectedTestId ? 'Selected' : 'Latest'} test #${current.test_number} / ${current.evaluation.passed ? 'Passed' : 'Failed'}` : 'No test yet';
  $('test-status').textContent = current ? (current.evaluation.passed ? 'PASSED' : 'FAILED') : 'WAITING'; $('test-status').className = `badge ${current?.evaluation?.passed ? '' : 'quiet'}`;
  $('test-metrics').className = current ? 'metric-grid' : 'metric-grid empty'; $('test-metrics').innerHTML = current ? Object.entries(metrics).map(([key, value]) => `<div class="metric"><span>${key.replaceAll('_', ' ')}</span><strong>${formatMetric(value, key)}</strong></div>`).join('') : 'No evaluation recorded.';
  $('open-current').hidden = !state.selectedTestId; $('open-current').textContent = 'Back to latest'; $('open-current').onclick = () => { state.selectedTestId = null; renderDashboard(); renderTests(); };
  const discovery = d.latest_discovery; $('discovery-text').textContent = discovery?.statement || 'No discovery recorded.'; $('confidence').textContent = discovery?.confidence || '--'; $('discovery-meta').textContent = discovery ? `${discovery.validation_status} / experiment ${discovery.source_experiment_id}` : '';
}
function renderTests() { $('library-count').textContent = `${state.tests.length} recorded`; $('tests').innerHTML = state.tests.length ? state.tests.map((test) => { const e = test.evaluation; const selected = state.selectedTestId === e.id ? ' selected' : ''; return `<div class="test-row${selected}" data-id="${e.id}"><div class="test-number">#${test.test_number}</div><div class="test-summary"><strong>${escapeHtml(test.candidate?.name || e.benchmark_id)} </strong><span>${escapeHtml(e.benchmark_id)} v${escapeHtml(e.benchmark_version)} · ${escapeHtml(test.experiment?.parameters?.strategy || 'experiment')}</span></div><div class="result ${e.passed ? 'pass' : 'fail'}">${e.passed ? 'PASS' : 'FAIL'} · ${Number(e.metrics.capability_score).toFixed(2)}</div></div>`; }).join('') : '<div class="empty-state">No experiments recorded yet.</div>'; document.querySelectorAll('.test-row').forEach((row) => row.onclick = () => { state.selectedTestId = row.dataset.id; renderDashboard(); renderTests(); }); }
function openModal(test) { if (!test) return; $('modal-title').textContent = `Test #${test.test_number} / ${test.evaluation.passed ? 'Passed' : 'Failed'}`; const e = test.evaluation, analysis = test.experiment?.analysis || {}; $('modal-body').innerHTML = `<div class="detail-section"><h4>Metrics</h4><pre>${escapeHtml(JSON.stringify(e.metrics, null, 2))}</pre></div><div class="detail-section"><h4>Experiment</h4><p>${escapeHtml(test.experiment?.hypothesis || '')}</p><pre>${escapeHtml(JSON.stringify(test.experiment?.parameters || {}, null, 2))}</pre></div><div class="detail-section"><h4>Discovery</h4><p>${escapeHtml(test.discovery?.statement || 'No discovery recorded.')}</p><pre>${escapeHtml(JSON.stringify(analysis, null, 2))}</pre></div>`; $('modal').hidden = false; }
$('close-modal').onclick = () => $('modal').hidden = true; $('modal').onclick = (event) => { if (event.target === $('modal')) $('modal').hidden = true; }; document.addEventListener('keydown', (event) => { if (event.key === 'Escape') $('modal').hidden = true; }); load().catch(() => { setHealth('OFFLINE'); $('headline').textContent = 'Backend unavailable'; $('subhead').textContent = 'Start Atlas with: py -3 -m atlas.cli web'; }); setInterval(load, 5000); setInterval(() => { if (state.lastSuccessAt && Date.now() - state.lastSuccessAt > 10000) setHealth('STALE'); }, 2000);