const state = { tests: [], dashboard: null, selectedTestId: null, lastSuccessAt: 0 };
const $ = (id) => document.getElementById(id);
const escapeHtml = (value) => String(value ?? '').replace(/[&<>"']/g, (char) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]));
const formatMetric = (value, key) => key.endsWith('_ms') ? `${Number(value).toFixed(1)} ms` : typeof value === 'number' ? value.toFixed(2) : value;

async function loadJson(path) { const response = await fetch(path); if (!response.ok) throw new Error(`${response.status} ${path}`); return response.json(); }
async function load() {
  let dashboard, tests, staticMode = false;
  try { [dashboard, tests] = await Promise.all([loadJson('/api/dashboard'), loadJson('/api/tests')]); }
  catch (error) { const snapshot = await loadJson(new URL('./data/dashboard.json', document.baseURI)); dashboard = snapshot.dashboard; tests = snapshot.tests; staticMode = true; }
  dashboard.static_mode = staticMode;
  state.dashboard = dashboard; state.tests = tests; state.lastSuccessAt = Date.now(); setHealth(staticMode ? 'STATIC' : 'ONLINE');
  if (state.selectedTestId && !tests.some((test) => test.evaluation.id === state.selectedTestId)) state.selectedTestId = null;
  renderDashboard(); renderTests();
}
function setHealth(status) { $('health-label').textContent = status; $('health').className = `live ${status.toLowerCase()}`; $('health-age').textContent = status === 'ONLINE' ? ' synced' : status === 'STALE' ? ' no recent sync' : status === 'OFFLINE' ? ' backend unavailable' : ' waiting for sync'; }
function renderDashboard() {
  const d = state.dashboard, current = state.tests.find((test) => test.evaluation.id === state.selectedTestId) || d.current_test, metrics = current?.evaluation?.metrics || {};
  const job = d.job || { status: 'idle' }; $('run-moe').hidden = d.static_mode; $('run-moe').disabled = job.status === 'running'; $('run-status').textContent = d.static_mode ? 'Static snapshot' : job.status === 'running' ? 'Running tensor mutation...' : job.status === 'succeeded' ? 'Iteration complete' : job.status === 'failed' ? `Failed: ${job.error}` : job.status === 'rejected' ? job.error : 'Ready';
  $('version').textContent = d.current_version ? `v${d.current_version.version}` : '--'; $('model-marker').textContent = `MODEL ${d.model || '--'}`;
  $('headline').textContent = d.model ? `${d.model} / ${d.test_counts.total ? `test ${d.current_test_number}` : 'ready'}` : 'Atlas is ready';
  $('subhead').textContent = d.current_version ? d.current_version.name : 'Initialize Atlas and run the first experiment.';
  $('stats').innerHTML = [['Evaluations', d.test_counts.total], ['Passed', d.test_counts.passed], ['Failed', d.test_counts.failed], ['Experiments', d.experiment_count]].map(([label, value]) => `<div class="stat"><label>${label}</label><strong>${escapeHtml(value)}</strong></div>`).join('');
  $('test-title').textContent = current ? `${state.selectedTestId ? 'Selected' : 'Latest'} test #${current.test_number} / ${current.evaluation.passed ? 'Passed' : 'Failed'}` : 'No test yet';
  $('test-status').textContent = current ? (current.evaluation.passed ? 'PASSED' : 'FAILED') : 'WAITING'; $('test-status').className = `badge ${current?.evaluation?.passed ? '' : 'quiet'}`;
  $('test-metrics').className = current ? 'metric-grid' : 'metric-grid empty'; $('test-metrics').innerHTML = current ? Object.entries(metrics).map(([key, value]) => `<div class="metric"><span>${key.replaceAll('_', ' ')}</span><strong>${formatMetric(value, key)}</strong></div>`).join('') : 'No evaluation recorded.';
  $('open-current').hidden = !state.selectedTestId; $('open-current').textContent = 'Back to latest'; $('open-current').onclick = () => { state.selectedTestId = null; renderDashboard(); renderTests(); };
  const discovery = d.latest_discovery; $('discovery-text').textContent = discovery?.statement || 'No discovery recorded.'; $('confidence').textContent = discovery?.confidence || '--'; $('discovery-meta').textContent = discovery ? `${discovery.validation_status} / experiment ${discovery.source_experiment_id}` : '';
}
function renderTests() { $('library-count').textContent = `${state.tests.length} recorded`; $('tests').innerHTML = state.tests.length ? state.tests.map((test) => { const e = test.evaluation; const selected = state.selectedTestId === e.id ? ' selected' : ''; return `<div class="test-row${selected}" data-id="${e.id}"><div class="test-number">#${test.test_number}</div><div class="test-summary"><strong>${escapeHtml(test.candidate?.name || e.benchmark_id)} </strong><span>${escapeHtml(e.benchmark_id)} v${escapeHtml(e.benchmark_version)} · ${escapeHtml(test.experiment?.parameters?.strategy || 'experiment')}</span></div><div class="result ${e.passed ? 'pass' : 'fail'}">${e.passed ? 'PASS' : 'FAIL'} · ${Number(e.metrics.capability_score).toFixed(2)}</div></div>`; }).join('') : '<div class="empty-state">No experiments recorded yet.</div>'; document.querySelectorAll('.test-row').forEach((row) => row.onclick = () => { state.selectedTestId = row.dataset.id; renderDashboard(); renderTests(); }); }
function openModal(test) { if (!test) return; $('modal-title').textContent = `Test #${test.test_number} / ${test.evaluation.passed ? 'Passed' : 'Failed'}`; const e = test.evaluation, summary = test.learned_summary || {}, analysis = test.experiment?.analysis || {}; $('modal-body').innerHTML = `<div class="detail-section"><h4>Metrics</h4><pre>${escapeHtml(JSON.stringify(e.metrics, null, 2))}</pre></div><div class="detail-section"><h4>What Atlas learned</h4><p>${escapeHtml(summary.what_learned || 'No learned summary recorded.')}</p><p class="muted">Next experiment: ${escapeHtml(summary.next_experiment || 'Not recorded')}</p></div><div class="detail-section"><h4>Experiment</h4><p>${escapeHtml(test.experiment?.hypothesis || '')}</p><pre>${escapeHtml(JSON.stringify(test.experiment?.parameters || {}, null, 2))}</pre></div><div class="detail-section"><h4>Discovery</h4><p>${escapeHtml(test.discovery?.statement || 'No discovery recorded.')}</p><pre>${escapeHtml(JSON.stringify(analysis, null, 2))}</pre></div><div class="detail-section"><h4>Model checkpoint</h4><pre>${escapeHtml(JSON.stringify(test.checkpoint || {status: 'not materialized'}, null, 2))}</pre></div>`; $('modal').hidden = false; }
$('close-modal').onclick = () => $('modal').hidden = true; $('modal').onclick = (event) => { if (event.target === $('modal')) $('modal').hidden = true; }; document.addEventListener('keydown', (event) => { if (event.key === 'Escape') $('modal').hidden = true; }); load().catch(() => { setHealth('OFFLINE'); $('headline').textContent = 'Backend unavailable'; $('subhead').textContent = 'Start Atlas with: py -3 -m atlas.cli web'; }); setInterval(load, 5000); setInterval(() => { if (state.lastSuccessAt && Date.now() - state.lastSuccessAt > 10000) setHealth('STALE'); }, 2000);
$('run-moe').onclick = async () => { $('run-moe').disabled = true; $('run-status').textContent = 'Queuing iteration...'; try { const response = await fetch('/api/moe/iterations', {method: 'POST'}); const contentType = response.headers.get('content-type') || ''; const body = await response.text(); if (!contentType.includes('application/json')) throw new Error(`Atlas API returned ${response.status} ${contentType || 'non-JSON'} response`); const payload = JSON.parse(body); if (!response.ok) { $('run-status').textContent = payload.error || 'Run rejected'; return; } await load(); } catch (error) { $('run-status').textContent = `Request failed: ${error.message}`; setHealth('OFFLINE'); } finally { $('run-moe').disabled = false; } };